apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello
  namespace: hello-ns
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hello-service
            port:
              number: 80
        path: /hello
        pathType: Exact
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.211
    - ip: 192.168.0.212
