apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-ns
spec:
  ports:
    - name: hello-world
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-app
  type: ClusterIP
