apiVersion: v1
kind: Pod
metadata:
  namespace: busybox-ns
  name: busybox
  labels:
    app: busybox
    tier: frontend
spec:
  containers:
     - name: busybox-container
       image: docker.io/busybox
       command: 
       - sh
       - "-c"
       - echo Hello world! && sleep 3600

